# Generated by Django 4.0.6 on 2022-07-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0002_alter_team_team_image'),
        ('activity', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('profile_image', models.ImageField(blank=True, default='users_photo/default_user.jpg', max_length=255, null=True, upload_to='users_photo')),
                ('age', models.IntegerField(null=True)),
                ('disponibility', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('prefer_activity', models.ManyToManyField(to='activity.activity')),
                ('user_events', models.ManyToManyField(to='event.event')),
                ('user_teams', models.ManyToManyField(to='team.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
