# Generated by Django 4.0.6 on 2022-07-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('event', '0001_initial'),
        ('team', '0002_alter_team_team_image'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='disponibility',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='prefer_activity',
            field=models.ManyToManyField(to='activity.activity'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='users_photo/default_user.jpg', max_length=255, null=True, upload_to='users_photo'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_events',
            field=models.ManyToManyField(to='event.event'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_teams',
            field=models.ManyToManyField(to='team.team'),
        ),
    ]
