# Generated by Django 4.0.6 on 2022-07-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_team_team_image'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teams_name',
            field=models.ManyToManyField(to='team.team'),
        ),
    ]
