# Generated by Django 4.0.6 on 2022-07-22 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_teams_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='teams_name',
        ),
    ]
