# Generated by Django 3.2.15 on 2022-09-02 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_team_created_at_team_updated_at'),
        ('users', '0005_auto_20220830_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_teams',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.CreateModel(
            name='Joined_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_user_user_teams',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='team_users',
            field=models.ManyToManyField(blank=True, related_name='users', through='users.Joined_team', to='team.Team'),
        ),
    ]
