# Generated by Django 3.2.15 on 2022-09-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220902_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibility_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='disponibility',
        ),
        migrations.AddField(
            model_name='user',
            name='user_disponibility',
            field=models.ManyToManyField(to='users.Disponibility'),
        ),
    ]
