# Generated by Django 3.2.15 on 2022-09-03 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banned_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banned_reason', models.TextField(max_length=1000)),
                ('date_banned', models.DateField(auto_now_add=True, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banned_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
