# Generated by Django 4.0.6 on 2022-07-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_sponsor', models.CharField(max_length=50)),
                ('image', models.ImageField(default='photos/22/07/14', upload_to='photos/%y/%m/%d')),
            ],
        ),
    ]
