# Generated by Django 4.0.6 on 2022-07-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_description', models.CharField(max_length=500)),
                ('post_date', models.DateTimeField()),
                ('post_location', models.CharField(max_length=200)),
                ('post_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='posts_photo')),
            ],
        ),
    ]
