# Generated by Django 4.0.6 on 2022-07-21 19:17

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
