# Generated by Django 4.0.6 on 2022-07-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='posts_photo/'),
        ),
    ]
