# Generated by Django 4.0.6 on 2022-07-21 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('post', '0004_alter_post_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
    ]
