# Generated by Django 4.0.6 on 2022-07-28 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
    ]
