# Generated by Django 4.0.6 on 2022-07-22 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_user_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
