# Generated by Django 3.2.15 on 2022-09-01 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0009_post_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_participants',
            name='user_id',
        ),
        migrations.AddField(
            model_name='post_participants',
            name='user_id',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
