# Generated by Django 3.2.15 on 2022-09-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('post', '0011_alter_post_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='activity.Category'),
        ),
    ]
