# Generated by Django 3.2.15 on 2022-09-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
