# Generated by Django 3.2.15 on 2022-09-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20220907_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_participants',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
