# Generated by Django 4.0.6 on 2022-07-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_image',
            field=models.ImageField(blank=True, default='teams_photo/default_team.jpg', max_length=255, null=True, upload_to='teams_photo'),
        ),
    ]
