# Generated by Django 4.0.6 on 2022-07-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_team_team_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_image',
            field=models.ImageField(blank=True, default='images/default_team.jpg.urls', max_length=255, null=True, upload_to='teams_photo'),
        ),
    ]
