# Generated by Django 4.0.6 on 2022-07-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_team_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_about',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
