# Generated by Django 4.0.6 on 2022-07-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_event',
            field=models.DateTimeField(null=True),
        ),
    ]
