# Generated by Django 3.2.15 on 2022-09-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_affiche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
